# Generated by Django 3.2 on 2022-06-20 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='accept_policy',
            new_name='accepted_privacy_policy',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='user',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='registered_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscriber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
