# Generated by Django 3.2 on 2022-07-20 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contactform_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['subscribed_on'], 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='accepted_privacy_policy',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='registered_user',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subscribed_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
